default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: onebitflx_development

test:
  <<: *default
  database: onebitflx_test

production:
  <<: *default
  database: onebitflx_production
  username: onebitflx
  password: <%= ENV['ONEBITFLX_DATABASE_PASSWORD'] %>
